### ISSUE TITLE
Check spelling

### ISSUE THREAD

**Issue by tiagoporto** [tiagoporto/generator-swill-boilerplate#29]
Check error in README.md

**Comment by mastercod3r** [comment]
Can I do this? Can you be more clear as in, what errors should I be looking for?

**Comment by tiagoporto** [comment]
Of course, please check grammatical errors.

**Comment by dhruvdutt** [comment]
#30 @tiagoporto 
Also, please add `hacktoberfest` label to the PR.

**Comment by christianhoward** [comment]
Hi, just took a look and submitted a PR. Let me know if you have any questions!

**Comment by hj222hi** [comment]
Hi i just added some fixes

[PR](https://github.com/tiagoporto/generator-swill-boilerplate/pull/38)
