### ISSUE TITLE
Default values and valid default code

### ISSUE THREAD

**Issue by ukozdan** [tiagoporto/generator-swill-boilerplate#46]
If, during setup, the user does not populate an option and instead hits "Enter" then values should fall-back to default values, e.g. page title to "untitled", logo anchor href to "http://www.somewhere.com" etc. 

The provided HTML, CSS and JavaScript should validate according to the installed rules.

**Comment by tiagoporto** [comment]
Hello @ukozdan, thanks for the issue.
What do you mean with `The provided HTML, CSS and JavaScript should validate according to the installed rules.`
Could you give me some examples?

**Comment by ukozdan** [comment]
Hi @tiagoporto, At least for the CSS, I was getting CSS style warnings, like the use of !important. While this isn't a syntax error, your default site should probably compile without any warnings, or errors, just for the sake of completing an already great job on the rest of the project.
